### ISSUE TITLE
Pandas library not loaded in the right sequence 

### ISSUE THREAD

**Issue by ougni** [lmoroney/dlaicourse#142]
Sun-spot data does not load here (pandas import issue)

https://github.com/lmoroney/dlaicourse/blob/master/TensorFlow%20In%20Practice/Course%204%20-%20S%2BP/S%2BP_Week_1_Lesson_2.ipynb

**Comment by emican** [comment]
ougni, try adding ```import pandas as pd``` to the cell.  Sunspots.csv can be downloaded from kaggle.
```
import pandas as pd
#https://www.kaggle.com/robervalt/sunspots?select=Sunspots.csv
df = pd.read_csv("Sunspots.csv", parse_dates=["Date"], index_col="Date")
series = df["Monthly Mean Total Sunspot Number"].asfreq("1M")
series.head()
```
