### ISSUE TITLE
One mistake in Exercise 5 - Answer.ipynb

### ISSUE THREAD

**Issue by ZhiliangWu** [lmoroney/dlaicourse#27]
For the [Exercise 5](https://github.com/lmoroney/dlaicourse/blob/master/Exercises/Exercise%205%20-%20Real%20World%20Scenarios/Exercise%205%20-%20Answer.ipynb) in Course 2, there is one mistake in the `split_data` function. 

```python
    ...
    training_set = shuffled_set[0:training_length]
    testing_set = shuffled_set[:testing_length]
    ...
```
   
* As we can see from the above code, the training set and testing set is overlapped with the same part of the data, which means that the testing data are no longer unseen data.

**Comment by JonathanSum** [comment]
Do you think the correction should be this?
`testing_set = shuffled_set[training_length:len(files)] .`


If so, I will pull a request and ask for a fix.

**Comment by ZhiliangWu** [comment]
Yes. Or simply `testing_set = shuffled_set[training_length:]`should be enough.

**Comment by JonathanSum** [comment]
I don't suggest to close the issue. Yes, I pulled the request, but Mr. lmoroney may think the problem is solved after he saw the issue was closed.
