### ISSUE TITLE
how  to save and load models that was trained using fit_generator

### ISSUE THREAD

**Issue by sleekmike** [lmoroney/dlaicourse#45]
Hello, 
I have been trying to reproduce the code(human or horse classification) in tensor flow in practise course (/Course 1 - Part 8 - Lesson 4 - Notebook.ipynb ) locally on my pc.
It works so far but when I save a model with this line:

history = model.fit_generator(
      train_generator,
      steps_per_epoch=8,  
      epochs=15,
      verbose=1,
      validation_data = validation_generator,
      validation_steps=8)

try:
    model.save_weights('human_horse1.h5')
except Exception as e:
    print("error in saving model: ", e)

and to load the saved:
new_model = tf.keras.models.load_model('human_horse3.h5')

if I try to used the saved model to predict with the code:

new_model.predict('./Users/macbook/Desktop/image_classifier/human01-04.png')

I normally get this error:
AttributeError: 'str' object has no attribute 'shape'

please how do I properly load and save models and use the model to predict locally on my pc. 
Kind regards.

**Comment by JonathanSum** [comment]
I am not really sure this can solve your issue. "shape" attribute is from numpy. Have you installed numpy yet?

**Comment by sleekmike** [comment]
Yes I have numpy and tensorflow 2.0 installed on my system.

**Comment by cicimeng** [comment]
why i can't install tensorflow 2.0 upgrade doesn't work 
    	
    	

    	Get Outlook for iOS
    
  




On Fri, Oct 4, 2019 at 9:40 PM +0800, "Mike Ohanu" <notifications@github.com> wrote:










Yes I have numpy and tensorflow 2.0 installed on my system.





On Fri, 4 Oct 2019 at 1:36 PM, Jonathan Sum <notifications@github.com>


wrote:

**Comment by JonathanSum** [comment]
I think the problem is this code 

And add these codes and use them:
`import numpy as np
from keras.preprocessing import image`

`img_width, img_height = 150, 150`
`img = image.load_img('./Users/macbook/Desktop/image_classifier/human01-04.png', target_size = (img_width, img_height))`
`img = image.img_to_array(img)`
`img = np.expand_dims(img, axis = 0)`
model.predict(img)

**Comment by sleekmike** [comment]
Thanks a lot @JonathanSum, I used your code and it works like magic :).
